### ISSUE TITLE
#1 Create List View

### ISSUE THREAD

**Issue by alexhu00** [agile-dev-assignments/project-setup-team-fridgey#10]
Related to user story #1.

## Subtasks
- [x] Create spoilage information chips
- [x] Create amount information chips
- [x] Create coloured freshness dot on left of items
- [ ] Create swipe to delete functionality
- [x] Create section headers
