### ISSUE TITLE
#1 Create Pop Up

### ISSUE THREAD

**Issue by saldanaj27** [agile-dev-assignments/project-setup-team-fridgey#20]
Related to user story #1.

### Subtasks

- [ ] Create amount information chips
- [ ] Create Add to Shopping List Button
- [ ] Create Use Within Dropdown Menu
- [ ] Create Notes section
- [ ] Create delete and save buttons
- [ ] Create exit button
- [ ] Create a freshness circle graph
- [ ] Create editable item name header
- [ ] Create date added field
